name: Delete Deployments
on:
  workflow_dispatch: # Allows manual triggering
jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      deployments: write
      contents: read
    steps:
      - name: Delete Deployment Environment
        uses: strumwolf/delete-deployment-environment@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment: 'vercel'
          onlyRemoveDeployments: true # Deletes deployments but keeps the environment